### ISSUE TITLE
Introduce proper k8s resources (CPU and Memory)

### ISSUE THREAD

**Issue by Nilegfx** [m3ntorship/pickify-posts#112]
### Story
Introduces memory and CPU requests/limits

### Tasks
- [x] CPU and memory declared as following 

```yaml
resources:
  limits:
    memory: "300"
  requests:
    cpu: "100"
	memory: "300" 
```
